### ISSUE TITLE
Logo For Optitravel

### ISSUE THREAD

**Issue by zularizal** [denysvitali/optitravel#2]
Hi @Raenilol I am a graphic designer, I want to help you in graphic design.

After I review your project, your app is very good. Therefore I suggest a logo and icon for you. If you want it, I will design it for you and it's free.

**Comment by denysvitali** [comment]
Hey! Thanks for your proposal.  
Sure, if you want to design a logo for free and you agree to release it under the MIT license, feel free to make a PR - and if we like it we'll merge your PR and include your logo in the README.md :+1:

**Comment by zularizal** [comment]
Hi @denysvitali , I've designed some logos for your project, which do you like? And what about color, do you want another color? If there is something that you want to change, let me know.

![logo](https://user-images.githubusercontent.com/38547278/41266473-2f7eeb24-6e21-11e8-899e-054cd882fe74.png)

**Comment by denysvitali** [comment]
First of all, thanks for your efforts! I really liked them all, but the second one (second of OT) is definitely the best one!  
  
I like its colors too, but maybe the dark green looks good if it's light green as the first OP logo.
Anyway: good work!  
  
May I have the logo in SVG and your name , so that I can add your full name to the contributors list - as a credit for the logo you've made?

**Comment by zularizal** [comment]
Hi, I have uploaded the logo file to drive, I have provided vector format for this logo (svg, ai, and eps)
https://drive.google.com/open?id=18V8mnyosj2OpiV80CPQamItoXvJ63PVJ

And also I have sent a pull request for you, check this #3

**Comment by denysvitali** [comment]
Thank you! I really like your work! I added the files you provided in `logo/logo.zip`. Feel free to add a link to your website or profile if you feel that the mention isn't enough :smiley:
